change how pgvm sets environment vars and checkout version

diff --git a/actions/cluster b/actions/cluster
--- a/actions/cluster
+++ b/actions/cluster
@@ -63,20 +63,20 @@ create()
 
     [[ -z "$cluster_name" ]] && echo "please, choose a name for cluster!" && exit 1
 
-    cluster_top_dir="$pgvm_home/clusters/${current}"
+    cluster_top_dir="${pgvm_clusters}/${current}"
     cluster_dir="${cluster_top_dir}/${cluster_name}"
 
     [[ -d "$cluster_dir" ]] && echo "cluster '${cluster_dir}' already exists!" && exit 1
 
     mkdir -p $cluster_top_dir
-    mkdir -p $pgvm_home/logs
+    mkdir -p $pgvm_logs
 
     echo -n "initializing cluster in '$cluster_dir'... "
-    $pgvm_home/environments/current/bin/initdb -D $cluster_dir $initdb_options 1> $pgvm_home/logs/install.$cluster_name@${current}.log 2>$pgvm_home/logs/install.$cluster_name@${current}.error.log
+    ${pgvm_environments}/current/bin/initdb -D $cluster_dir $initdb_options 1> ${pgvm_logs}/install.$cluster_name@${current}.log 2>${pgvm_logs}/install.$cluster_name@${current}.error.log
 
-    [[ $? -ne 0 ]] && echo "error!" && cat $pgvm_home/logs/install.$cluster_name@${current}.error.log && exit 1
+    [[ $? -ne 0 ]] && echo "error!" && cat ${pgvm_logs}/install.$cluster_name@${current}.error.log && exit 1
 
-    last_port=$(find $pgvm_home/clusters -name "postgresql.conf" -exec egrep "port =" {} \; | awk '{ printf $3"\n" ;}' | sort -n | tail -1)
+    last_port=$(find ${pgvm_clusters} -name "postgresql.conf" -exec egrep "port =" {} \; | awk '{ printf $3"\n" ;}' | sort -n | tail -1)
     next_port=$(($last_port + 1))
 
     echo -e "\n# added by 'pgvm' at `date`" >> $cluster_dir/postgresql.conf
@@ -88,7 +88,7 @@ create()
 list()
 {
     current=$(current_version)
-    cluster_top_dir="$pgvm_home/clusters/${current}"
+    cluster_top_dir="${pgvm_clusters}/${current}"
     clusters=$(find ${cluster_top_dir}/* -maxdepth 0 -type d -exec basename {} \; 2> /dev/null)
 
     [[ -z "$clusters" ]] && echo "there is no clusters in current environment (${current})" && exit 1
@@ -130,7 +130,7 @@ status()
 use()
 {
     echo "not implemented" && exit 1
-    cluster_top_dir="$pgvm_home/clusters/$(current_version)"
+    cluster_top_dir="${pgvm_clusters}/$(current_version)"
     cluster_name=${1}
     cluster="${cluster_top_dir}/${cluster_name}"
 
@@ -139,7 +139,7 @@ use()
 
 remove()
 {
-    cluster_top_dir="$pgvm_home/clusters/$(current_version)"
+    cluster_top_dir="${pgvm_clusters}/$(current_version)"
     cluster_name=${1} ; shift
     cluster="${cluster_top_dir}/${cluster_name}"
     rest=${1}
@@ -165,10 +165,10 @@ cluster_ctl()
 {
     action=$1
     cluster_name=$2
-    cluster_top_dir="$pgvm_home/clusters/$(current_version)"
+    cluster_top_dir="${pgvm_clusters}/$(current_version)"
     cluster_dir=${cluster_top_dir}/${cluster_name}
 
-    $pgvm_home/environments/current/bin/pg_ctl --silent -w -D $cluster_dir $action || exit 1
+    ${pgvm_environments}/current/bin/pg_ctl --silent -w -D $cluster_dir $action || exit 1
 }
 
 cluster_human_status()
@@ -177,10 +177,10 @@ cluster_human_status()
 
     cluster_name=$1
     cluster_version=${2:-$(current_version)}
-    cluster_top_dir="$pgvm_home/clusters/$cluster_version"
+    cluster_top_dir="${pgvm_clusters}/$cluster_version"
     cluster_dir=${cluster_top_dir}/${cluster_name}
 
-    $pgvm_home/environments/$cluster_version/bin/pg_ctl -D $cluster_dir status 1>/dev/null 2>/dev/null && echo "online" || echo "offline"
+    ${pgvm_environments}/$cluster_version/bin/pg_ctl -D $cluster_dir status 1>/dev/null 2>/dev/null && echo "online" || echo "offline"
 }
 
 cluster_port()
@@ -189,7 +189,7 @@ cluster_port()
 
     cluster_name=$1
     cluster_version=${2:-$(current_version)}
-    cluster_top_dir="$pgvm_home/clusters/$cluster_version"
+    cluster_top_dir="${pgvm_clusters}/$cluster_version"
     cluster_dir=${cluster_top_dir}/${cluster_name}
 
     cluster_port=$(egrep "^\s*port\s*=" $cluster_dir/postgresql.conf)
diff --git a/bin/pgvm-self-install b/bin/pgvm-self-install
--- a/bin/pgvm-self-install
+++ b/bin/pgvm-self-install
@@ -22,61 +22,67 @@
 # updates, enhancements, or modifications.
 
 ACTUAL_DIR=`pwd`
+STABLE_VERSION="tags/v0.2.0"
 
 clone_repo()
 {
   echo
   echo -n "wait while the installer fetches pgvm's files ..."
-  git clone git://github.com/guedes/pgvm.git $pgvm_home 2> /dev/null
+  git clone git://github.com/guedes/pgvm.git $pgvm_home > /dev/null 2>&1 || {
+    echo "sorry, pgvm could not be installed" && exit 1
+  }
 
-  [[ $? -eq 0 ]] && echo "done" || echo "sorry, pgvm could not be installed"
+  cd $pgvm_home && git checkout $STABLE_VERSION > /dev/null 2>&1 && echo " done" || {
+    echo "sorry, your git could not checkout from '$STABLE_VERSION'" && exit 1
+  }
+
 }
 
 update_repo()
 {
 	cd $pgvm_home
-	git pull origin master
+	git checkout $STABLE_VERSION > /dev/null 2>&1 && \
+      git pull origin $STABLE_VERSION > /dev/null 2>&1 || \
+        echo "sorry, pgvm could not checkout from '$STABLE_VERSION'"
 }
 
 force_clone_repo()
 {
-	rm -rf $pgvm_home
-	clone_repo
+  echo "DEPRECATED! Please use --update instead"
 }
 
 set_bashrc_env()
 {
-  pgvm_home="export pgvm_home=$pgvm_home"
-  path="export PATH=\$pgvm_home/bin:\$PATH"
-  path_env="export PATH=\$pgvm_home/environments/current/bin:\$PATH"
+  [[ -f $HOME/.bashrc ]] || touch $HOME/.bashrc
 
-  if ! egrep "export (pgvm_home|PATH=\$pgvm_home)" $HOME/.bashrc >/dev/null
-  then
-    echo $pgvm_home >> $HOME/.bashrc
-    echo $path >> $HOME/.bashrc
-    echo $path_env >> $HOME/.bashrc
-  fi
+  egrep "source .*pgvm_env.*" $HOME/.bashrc >/dev/null \
+    || echo "source ${pgvm_home}/pgvm_env" >> $HOME/.bashrc
 }
 
 set_bash_profile_env()
 {
-  pgvm_home="export pgvm_home=$pgvm_home"
-  path="export PATH=\$pgvm_home/bin:\$PATH"
-  path_env="export PATH=\$pgvm_home/environments/current/bin:\$PATH"
-
   [[ -f $HOME/.bash_profile ]] || touch $HOME/.bash_profile
 
-  if ! egrep "export (pgvm_home|PATH=\$pgvm_home)" $HOME/.bash_profile >/dev/null
-  then
-    echo $pgvm_home >> $HOME/.bash_profile
-    echo $path >> $HOME/.bash_profile
-    echo $path_env >> $HOME/.bash_profile
-  fi
+  egrep "source .*pgvm_env.*" $HOME/.bash_profile >/dev/null \
+    || echo "source ${pgvm_home}/pgvm_env" >> $HOME/.bash_profile
 }
 
 set_bash_env()
 {
-  echo -n "setting the environment ..."
+  echo -n "setting up the environment ..."
+
+  cat > ${pgvm_home}/pgvm_env <<EOF
+pgvm_home=${pgvm_home}
+pgvm_logs=${pgvm_logs}
+pgvm_clusters=${pgvm_clusters}
+pgvm_environments=${pgvm_environments}
+
+export pgvm_home pgvm_logs pgvm_environments pgvm_clusters
+
+export PATH=\${pgvm_home}/bin:\$PATH
+export PATH=\${pgvm_environments}/current/bin:\$PATH
+EOF
+
   case $OSTYPE in
     darwin*) set_bash_profile_env ;;
           *) set_bashrc_env ;;
@@ -103,6 +109,9 @@ parse_options()
 parse_options $*
 
 pgvm_home=${opt_pgvm_home:-"$HOME/.pgvm"}
+pgvm_logs=${opt_pgvm_logs:-"\${pgvm_home}/logs"}
+pgvm_clusters=${opt_pgvm_clusters:-"\${pgvm_home}/clusters"}
+pgvm_environments=${opt_pgvm_environments:-"\${pgvm_home}/environments"}
 
 echo "PostgreSQL version manager's installer"
 
