now we can create, start and stop clusters! :love:

diff --git a/actions/cluster b/actions/cluster
--- a/actions/cluster
+++ b/actions/cluster
@@ -63,11 +63,18 @@ create()
 	[[ -d "$cluster_dir" ]] && echo "cluster '${cluster_dir}' already exists!" && exit 1
 
 	mkdir --parents $cluster_top_dir
+	mkdir --parents $pgvm_home/logs
 
 	echo -n "initializing cluster in '$cluster_dir'... "
-	$pgvm_home/environments/current/bin/initdb -D $cluster_dir 1> $cluster_top_dir/install.$cluster_name.log 2>$cluster_top_dir/install.$cluster_name.error.log
+	$pgvm_home/environments/current/bin/initdb -D $cluster_dir 1> $pgvm_home/logs/install.$cluster_name@$(current).log 2>$pgvm_home/logs/install.$cluster_name@$(current).error.log
 
-	[[ $? -ne 0 ]] && echo "error!" && cat $cluster_dir/install.error.log
+	[[ $? -ne 0 ]] && echo "error!" && cat $pgvm_home/logs/install.$cluster_name@$(current).error.log && exit 1
+
+	last_port=$(find $pgvm_home/clusters -name "postgresql.conf" -exec egrep "port =" {} \; | awk '{ printf $3"\n" ;}' | sort -n | tail -1)
+	next_port=$(($last_port + 1))
+
+	echo -e "\n# added by 'pgvm' at `date`" >> $cluster_dir/postgresql.conf
+	echo "port = $next_port" >> $cluster_dir/postgresql.conf
 
 	echo "ok!"
 }
@@ -77,26 +84,50 @@ list()
 	cluster_top_dir="$pgvm_home/clusters/$(current)"
 	clusters=$(find ${cluster_top_dir}/* -maxdepth 0 -type d -exec basename {} \; 2> /dev/null)
 
+	[[ -z "$clusters" ]] && echo "there is no clusters in current environment ($(current))" && exit 1
+
+	echo -e "cluster in current enviroment ($(current)):\n"
+
 	for cluster in ${clusters}
 	do
 		echo "$cluster"
 	done
 }
 
+start()
+{
+	cluster_ctl start $1
+}
+
+stop()
+{
+	cluster_ctl stop $1
+}
+
+cluster_ctl()
+{
+	action=$1
+	cluster_name=$2
+	cluster_top_dir="$pgvm_home/clusters/$(current)"
+	cluster_dir=${cluster_top_dir}/${cluster_name}
+
+	$pgvm_home/environments/current/bin/pg_ctl -D $cluster_dir $action
+}
+
 use()
 {
+	echo "not implemented" && exit 1
 	cluster_top_dir="$pgvm_home/clusters/$(current)"
 	cluster_name=${1}
 	cluster="${cluster_top_dir}/${cluster_name}"
 
 	[[ -f "$cluster/PG_VERSION" ]] && [[ ! -e "$cluster/" ]]
-	alias teste="$cluster"
 }
 
 remove()
 {
+	echo "not implemented" && exit 1
 	cluster=${1}
-
 
 	echo -n "removing cluster '$cluster'"
 }
